type = "train"

[data]
[data.train]
dir = "data"
file = "train.csv"
batch_size = 8
shuffle = true

[data.valid]
dir = "data"
file = "valid.csv"
batch_size = 32
shuffle = false

[optimizer]
lr = 0.01
momentum = 0
nesterov = false

[model]
_ = '''
    For this particular example, the model is
        already fixed. Therefore no configuration
        for the iris logistic regression model.
'''

[loss]
_ = '''
    For this particular example, the loss function 
        already fixed as CrossEntropyLoss. Therefore 
        no further configuration.
'''

[train]
max_epoch = 10
log_interval = 2
